# Generated by Django 5.1.5 on 2025-02-03 01:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_persona_creacion_persona_ultima_actualizacion'),
        ('propiedad', '0004_propiedad_creacion_propiedad_ultima_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('frecuencia_actualizacion', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='ActualizacionAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField(default=django.utils.timezone.now)),
                ('porcentaje_aumento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nuevo_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato')),
            ],
            options={
                'verbose_name': 'Actualziacion de Alquiler',
                'verbose_name_plural': 'Actualziaciones de Alquileres',
            },
        ),
    ]
