# Generated by Django 5.1.5 on 2025-02-03 03:24

import django.db.models.deletion
import imagekit.models.fields
import imagen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0001_initial'),
        ('propiedad', '0004_propiedad_creacion_propiedad_ultima_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', imagekit.models.fields.ProcessedImageField(upload_to=imagen.models.upload_to_propiedad)),
                ('portada', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
