# Generated by Django 5.1.5 on 2025-03-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0002_imagenpropiedad_delete_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpropiedad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
