# Generated by Django 5.1.5 on 2025-03-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='metodos_pago',
            field=models.CharField(blank=True, help_text='Métodos de pago aceptados, separados por comas', max_length=255, null=True),
        ),
    ]
