# Generated by Django 5.1.5 on 2025-03-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_creacion_persona_ultima_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='pais',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('BRA', 'Brasil'), ('CHI', 'Chile'), ('PER', 'Perú'), ('URU', 'Uruguay'), ('PAR', 'Paraguay'), ('BOL', 'Bolivia')], default='ARG', max_length=50),
        ),
    ]
