# Generated by Django 5.1.5 on 2025-02-02 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERICO', 'Numérico'), ('BOOLEANO', 'Booleano')], max_length=10)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=100)),
                ('numeracion', models.CharField(blank=True, default='S/N', max_length=10, null=True)),
                ('piso', models.CharField(blank=True, max_length=5, null=True)),
                ('departamento', models.CharField(blank=True, max_length=5, null=True)),
                ('ciudad', models.CharField(default='Córdoba', max_length=50)),
                ('provincia', models.CharField(default='Córdoba', max_length=50)),
                ('pais', models.CharField(default='Argentina', max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('LOCAL COMERCIAL', 'Local Comercial'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno'), ('GALPON', 'Galpón'), ('FONDO DE COMERCIO', 'Fondo de Comercio'), ('HOTEL', 'Hotel'), ('COCHERA', 'Cochera'), ('OTRO', 'Otro')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('alquiler_venta', models.CharField(choices=[('ALQUILER', 'Alquiler'), ('VENTA', 'Venta'), ('ALQUILER/VENTA', 'Alquiler/Venta')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.atributo')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
        ),
    ]
