# Generated by Django 5.1.5 on 2025-02-02 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '__first__'),
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='dueño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
