# Generated by Django 5.1.5 on 2025-02-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_propiedad_dueño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributo',
            old_name='tipo',
            new_name='tipo_dato',
        ),
    ]
