# Generated by Django 5.1.5 on 2025-02-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0004_propiedad_creacion_propiedad_ultima_actualizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoratributo',
            name='atributo',
        ),
        migrations.RemoveField(
            model_name='valoratributo',
            name='propiedad',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='antiguedad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='baños',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cocheras',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='dormitorios',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='habitaciones',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='piscina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='pisos',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Atributo',
        ),
        migrations.DeleteModel(
            name='ValorAtributo',
        ),
    ]
