# Generated by Django 5.1.5 on 2025-02-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0005_remove_valoratributo_atributo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
