# Generated by Django 5.1.5 on 2025-03-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0006_alter_propiedad_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='habitaciones',
            new_name='ambientes',
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='nombre',
            new_name='denominacion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='precio',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='barrio',
            field=models.CharField(default='Barrio Falso', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_alquiler',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
