# Generated by Django 5.1.5 on 2025-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0007_rename_habitaciones_propiedad_ambientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='metros_cuadrados',
            new_name='metros_totales',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros_cubiertos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros_descubiertos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
